apiVersion: gcp.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    render.crossplane.io/composition-path: apis/cluster/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
  name: platform-ref-gcp
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    id: platform-ref-gcp
    region: us-west2
    version: latest
    nodes:
      count: 1
      instanceType: n1-standard-4
    gitops:
      git:
        url: https://github.com/upbound/platform-ref-gcp/
        ref:
          # refs/heads/main
          # refs/tags/v0.1.0
          # refs/pull/420/head
          # refs/merge-requests/1/head
          name: refs/heads/main
  writeConnectionSecretToRef:
    name: platform-ref-gcp-kubeconfig
